
#Backend Services
services:
  backend:
    build: .
    container_name: mechanic_backend

    ports:
      - "3000:3000"

    environment:
      PORT: 3000

    volumes:
      - ./data:/app/data

    restart: unless-stopped